In [2]:
import pandas as pd

In [3]:
prices = pd.Series([55000, 25000, 2500, 1800, 15000, 900])

print("PRODUCT PRICES")
print(prices)

PRODUCT PRICES
0    55000
1    25000
2     2500
3     1800
4    15000
5      900
dtype: int64

In [4]:
product_prices = pd.Series(
    [55000, 25000, 2500, 1800, 15000, 900],
    index=["Laptop", "Smartphone", "Headphones",
           "Keyboard", "Monitor", "Mouse"]
)

print("\nPRODUCT PRICES WITH CUSTOM INDEX")
print(product_prices)

PRODUCT PRICES WITH CUSTOM INDEX
Laptop        55000
Smartphone    25000
Headphones     2500
Keyboard       1800
Monitor       15000
Mouse           900
dtype: int64

In [5]:
print("\nSERIES ACCESS")

print("Third product price:", prices.iloc[2])

print("Laptop price:", product_prices["Laptop"])

print("\nFirst three product prices:")
print(prices.iloc[0:3])

SERIES ACCESS
Third product price: 2500
Laptop price: 55000

First three product prices:
0    55000
1    25000
2     2500
dtype: int64

In [6]:
data = {
    "Product_ID": ["P101", "P102", "P103", "P104", "P105", "P106"],
    "Product": [
        "Laptop", "Smartphone", "Headphones",
        "Keyboard", "Monitor", "Mouse"
    ],
    "Category": [
        "Electronics", "Electronics", "Accessories",
        "Accessories", "Electronics", "Accessories"
    ],
    "Price": [55000, 25000, 2500, 1800, 15000, 900],
    "Quantity": [3, 5, 10, 8, 4, 15],
    "Rating": [4.5, 4.2, 4.0, 4.3, 4.6, 4.1]
}

df = pd.DataFrame(data)

print(df)

  Product_ID     Product     Category  Price  Quantity  Rating
0       P101      Laptop  Electronics  55000         3     4.5
1       P102  Smartphone  Electronics  25000         5     4.2
2       P103  Headphones  Accessories   2500        10     4.0
3       P104    Keyboard  Accessories   1800         8     4.3
4       P105     Monitor  Electronics  15000         4     4.6
5       P106       Mouse  Accessories    900        15     4.1

In [7]:
df

  Product_ID     Product     Category  Price  Quantity  Rating
0       P101      Laptop  Electronics  55000         3     4.5
1       P102  Smartphone  Electronics  25000         5     4.2
2       P103  Headphones  Accessories   2500        10     4.0
3       P104    Keyboard  Accessories   1800         8     4.3
4       P105     Monitor  Electronics  15000         4     4.6
5       P106       Mouse  Accessories    900        15     4.1

In [8]:
print("\nSINGLE COLUMN - PRICE")
print(df["Price"])

print("\nMULTIPLE COLUMNS")
print(df[["Product", "Category", "Price"]])

SINGLE COLUMN - PRICE
0    55000
1    25000
2     2500
3     1800
4    15000
5      900
Name: Price, dtype: int64

MULTIPLE COLUMNS
      Product     Category  Price
0      Laptop  Electronics  55000
1  Smartphone  Electronics  25000
2  Headphones  Accessories   2500
3    Keyboard  Accessories   1800
4     Monitor  Electronics  15000
5       Mouse  Accessories    900

In [9]:
print("\nPRODUCTS WITH PRICE > 10000")
print(df[df["Price"] > 10000])

print("\nPRODUCTS WITH RATING > 4.3")
print(df[df["Rating"] > 4.3])

print("\nPRODUCTS WITH QUANTITY > 5")
print(df[df["Quantity"] > 5])

print("\nELECTRONICS PRODUCTS")
print(df[df["Category"] == "Electronics"])

PRODUCTS WITH PRICE > 10000
  Product_ID     Product     Category  Price  Quantity  Rating
0       P101      Laptop  Electronics  55000         3     4.5
1       P102  Smartphone  Electronics  25000         5     4.2
4       P105     Monitor  Electronics  15000         4     4.6

PRODUCTS WITH RATING > 4.3
  Product_ID  Product     Category  Price  Quantity  Rating
0       P101   Laptop  Electronics  55000         3     4.5
4       P105  Monitor  Electronics  15000         4     4.6

PRODUCTS WITH QUANTITY > 5
  Product_ID     Product     Category  Price  Quantity  Rating
2       P103  Headphones  Accessories   2500        10     4.0
3       P104    Keyboard  Accessories   1800         8     4.3
5       P106       Mouse  Accessories    900        15     4.1

ELECTRONICS PRODUCTS
  Product_ID     Product     Category  Price  Quantity  Rating
0       P101      Laptop  Electronics  55000         3     4.5
1       P102  Smartphone  Electronics  25000         5     4.2
4       P105     Monitor  Electronics  15000         4     4.6

In [10]:
print("\nSPECIFIC CELL")
print("First product:", df.at[0, "Product"])
print("First product price:", df.at[0, "Price"])

SPECIFIC CELL
First product: Laptop
First product price: 55000

In [11]:
df["Sales_Amount"] = df["Price"] * df["Quantity"]

print("\nDATA WITH SALES AMOUNT")
print(df)

DATA WITH SALES AMOUNT
  Product_ID     Product     Category  Price  Quantity  Rating  Sales_Amount
0       P101      Laptop  Electronics  55000         3     4.5        165000
1       P102  Smartphone  Electronics  25000         5     4.2        125000
2       P103  Headphones  Accessories   2500        10     4.0         25000
3       P104    Keyboard  Accessories   1800         8     4.3         14400
4       P105     Monitor  Electronics  15000         4     4.6         60000
5       P106       Mouse  Accessories    900        15     4.1         13500

In [12]:
total_sales = df["Sales_Amount"].sum()
average_price = df["Price"].mean()
highest_price = df["Price"].max()
lowest_price = df["Price"].min()
total_quantity = df["Quantity"].sum()

print("\nSALES STATISTICS")
print("Total Sales:", total_sales)
print("Average Price:", round(average_price, 2))
print("Highest Price:", highest_price)
print("Lowest Price:", lowest_price)
print("Total Quantity Sold:", total_quantity)

SALES STATISTICS
Total Sales: 402900
Average Price: 16700.0
Highest Price: 55000
Lowest Price: 900
Total Quantity Sold: 45

In [13]:
best_selling_index = df["Quantity"].idxmax()
best_selling_product = df.loc[best_selling_index, "Product"]

highest_rated_index = df["Rating"].idxmax()
highest_rated_product = df.loc[highest_rated_index, "Product"]

print("\nBEST-SELLING PRODUCT")
print(best_selling_product)

print("\nHIGHEST-RATED PRODUCT")
print(highest_rated_product)

BEST-SELLING PRODUCT
Mouse

HIGHEST-RATED PRODUCT
Monitor

In [14]:
category_sales = df.groupby("Category")["Sales_Amount"].sum()

print("\nSALES BY CATEGORY")
print(category_sales)

SALES BY CATEGORY
Category
Accessories     52900
Electronics    350000
Name: Sales_Amount, dtype: int64

In [25]:
monthly_sales = pd.read_excel("/Users/arjunaji/BIA ARJUN/ASSIGNMENTS/Data/04_monthly_sales.xlsx")
monthly_sales

      Month  Total_Orders  Total_Sales  Average_Order_Value
0   January           120       325000                 2708
1  February           145       410000                 2828
2     March           160       455000                 2844
3     April           138       380000                 2754
4       May           175       520000                 2971
5      June           190       575000                 3026

In [26]:
monthly_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Month                6 non-null      str
 1   Total_Orders         6 non-null      int64
 2   Total_Sales          6 non-null      int64
 3   Average_Order_Value  6 non-null      int64
dtypes: int64(3), str(1)
memory usage: 324.0 bytes

In [27]:
sales_data= pd.read_csv("/Users/arjunaji/BIA ARJUN/ASSIGNMENTS/Data/sales_data.csv")
sales_data

       product     category    price  quantity   sales  rating        date
0       Laptop  Electronics  55000.0         2  110000     4.5  2026-01-01
1        Phone  Electronics  25000.0         5  125000     4.2  2026-01-02
2       Tablet  Electronics  18000.0         3   54000     NaN  2026-01-03
3       Laptop  Electronics  55000.0         1   55000     4.7  2026-01-04
4   Headphones  Accessories   2500.0        10   25000     4.1  2026-01-05
5        Phone  Electronics  25000.0         4  100000     4.3  2026-01-06
6       Tablet  Electronics  18000.0         2   36000     3.9  2026-01-07
7   Headphones  Accessories      NaN         8   20000     4.0  2026-01-08
8       Laptop  Electronics  55000.0         3  165000     4.8  2026-01-09
9        Phone  Electronics  25000.0         6  150000     4.4  2026-01-10
10    Keyboard  Accessories   1500.0         7   10500     4.0  2026-01-11
11       Mouse  Accessories    900.0        12   10800     4.2  2026-01-12

In [28]:
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   12 non-null     str
 1   category  12 non-null     str
 2   price     11 non-null     float64
 3   quantity  12 non-null     int64
 4   sales     12 non-null     int64
 5   rating    11 non-null     float64
 6   date      12 non-null     str
dtypes: float64(2), int64(2), str(3)
memory usage: 804.0 bytes

In [ ]:
print("          FINAL SALES REPORT\n")
print("Total Products:", len(df))
print("Total Quantity Sold:", total_quantity)
print("Total Sales:", total_sales)
print("Average Product Price:", round(average_price, 2))
print("Highest Product Price:", highest_price)
print("Lowest Product Price:", lowest_price)
print("Best-Selling Product:", best_selling_product)
print("Highest-Rated Product:", highest_rated_product)

print("\nSales by Category:")
print(category_sales)

          FINAL SALES REPORT

Total Products: 6
Total Quantity Sold: 45
Total Sales: 402900
Average Product Price: 16700.0
Highest Product Price: 55000
Lowest Product Price: 900
Best-Selling Product: Mouse
Highest-Rated Product: Monitor

Sales by Category:
Category
Accessories     52900
Electronics    350000
Name: Sales_Amount, dtype: int64