# LIBRARIES

## NumPy(Numerical Python)

##### NumPy (Numerical Python) is a fundamental library in Python for numerical and scientific computing.

In [1]:
import numpy as np

In [3]:
array_1=np.array([1,2,3,4,5,6])

In [4]:
type(array_1)

numpy.ndarray

In [5]:
array_2=np.array(["One","Hi","Arjun"])

In [6]:
array_2

array(['One', 'Hi', 'Arjun'], dtype='<U5')

In [7]:
array_1.dtype

dtype('int64')

In [8]:
array_2.dtype

dtype('<U5')

In [9]:
array_3=np.array([12,3,4.5,6.6])

In [10]:
array_3.dtype

dtype('float64')

In [11]:
array_4=np.array([12,4,2.6,4.7,"Arjun"])

In [12]:
array_4

array(['12', '4', '2.6', '4.7', 'Arjun'], dtype='<U32')

In [13]:
array_1[2]

np.int64(3)

In [14]:
array_1[-1]

np.int64(6)

In [15]:
array_1[0:2]

array([1, 2])

In [16]:
 array_1.shape

(6,)

In [17]:
array_1.ndim

1

In [18]:
scores=np.array([34,44,33,42,35,46])

In [19]:
scores.sum()

np.int64(234)

In [20]:
scores.min()

np.int64(33)

In [21]:
scores.max()

np.int64(46)

In [22]:
np.sum(scores)

np.int64(234)

In [23]:
scores.mean()

np.float64(39.0)

In [24]:
np.average(scores)

np.float64(39.0)

In [27]:
print("SUM     : ",scores.sum())

print("MINIMUM : ",scores.min())

print("MAXIMUM : ",scores.max())

print("AVERAGE : ",scores.mean())

SUM     :  234
MINIMUM :  33
MAXIMUM :  46
AVERAGE :  39.0

In [31]:
salary=np.array([1200,3000,4000,2000])

In [32]:
salary_updated= salary+ salary*0.1

In [34]:
salary_updated

array([1320., 3300., 4400., 2200.])

In [39]:
salary_updated2= salary*1.1

In [36]:
salary_updated2

array([1320., 3300., 4400., 2200.])

In [37]:
salary[0]*1.1

np.float64(1320.0)

In [40]:
zeros_1d=np.zeros(10)

In [41]:
zeros_1d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
ones_1d=np.ones(10)

In [44]:
ones_1d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
even_arr=np.arange(2,31,2)
even_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [53]:
odd_arr=np.arange(1,30,2)
odd_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [56]:
tens_arr=np.ones(10)*10
tens_arr

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [57]:
even_arr+odd_arr

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59])

In [58]:
even_arr-odd_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
odd_arr-even_arr

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [60]:
even_arr*odd_arr

array([  2,  12,  30,  56,  90, 132, 182, 240, 306, 380, 462, 552, 650,
       756, 870])

In [63]:
array_2d=np.array([[12,13,14],
         [54,32,5]])

In [64]:
array_2d

array([[12, 13, 14],
       [54, 32,  5]])

In [65]:
array_2d.shape

(2, 3)

In [66]:
array_2d.ndim

2

In [74]:
array_2d[1,2]

np.int64(5)

In [71]:
array_2d[1]

array([54, 32,  5])

In [72]:
array_2d[:,1]

array([13, 32])

In [73]:
array_2d[:,1:3]

array([[13, 14],
       [32,  5]])

In [75]:
ones_1d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [76]:
array_1_2d=np.array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],ndmin=2)

In [77]:
array_1_2d.shape

(1, 10)

In [79]:
array_1_2d.reshape(10,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [80]:
array_1_2d.reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
array_1_2d.reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [83]:
scores>40

array([False,  True, False,  True, False,  True])

## PANDAS

##### Pandas is a Python library designed for data manipulation and analysis.

In [84]:
import pandas as pd

In [90]:
sr_1=pd.Series([12,39,35,26])
sr_1

0    12
1    39
2    35
3    26
dtype: int64

In [89]:
sr_2=pd.Series(array_1)
sr_2

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [91]:
sr_2[0]

np.int64(1)

In [92]:
sr_2[0:3]

0    1
1    2
2    3
dtype: int64

In [95]:
sr_2_indexing=pd.Series(array_1,index=["A","B","C","D","E","F"])
sr_2_indexing

A    1
B    2
C    3
D    4
E    5
F    6
dtype: int64

In [96]:
sr_2_indexing.loc["A"]

np.int64(1)

In [97]:
sr_2_indexing.iloc[0]

np.int64(1)

In [98]:
sr_2_indexing["A"]

np.int64(1)

In [104]:
dict_data={"NAME":["ARJUN","ANAND","AJMAL"],
           "AGE":[21,20,22]
          }

In [106]:
df= pd.DataFrame(dict_data)
df

    NAME  AGE
0  ARJUN   21
1  ANAND   20
2  AJMAL   22

In [107]:
array_2

array(['One', 'Hi', 'Arjun'], dtype='<U5')

In [108]:
array_3

array([12. ,  3. ,  4.5,  6.6])

In [112]:
df_2= pd.DataFrame(array_3,columns=["Col A"])
df_2

   Col A
0   12.0
1    3.0
2    4.5
3    6.6